'use strict';

const assert = require('assert');
const API = require('./api');

describe('Country', function () {
    before(() => {
        require('../../app/index');
    });

    it('get all countries', (done) => {
        API.getCountries()
            .then(res => {
                assert.deepEqual(res.body,
                    [
                        'Albania',
                        'Algeria',
                        'Antigua and Barbuda',
                        'Argentina',
                        'Australia',
                        'Austria',
                        'Bahamas',
                        'Bahrain',
                        'Bangladesh',
                        'Barbados',
                        'Belgium',
                        'Bolivia',
                        'Brazil',
                        'Bulgaria',
                        'Cameroon',
                        'Canada',
                        'Catalonia',
                        'Chile',
                        'China',
                        'Colombia',
                        'Costa Rica',
                        'Croatia',
                        'Cyprus',
                        'Czech Republic',
                        'Denmark',
                        'Dominican Republic',
                        'Ecuador',
                        'Egypt',
                        'El Salvador',
                        'Estonia',
                        'Finland',
                        'France',
                        'Germany',
                        'Greece',
                        'Grenada',
                        'Guadeloupe',
                        'Guam',
                        'Guatemala',
                        'Hashemite Kingdom of Jordan',
                        'Honduras',
                        'Hong Kong',
                        'Hungary',
                        'India',
                        'Indonesia',
                        'Iraq',
                        'Ireland',
                        'Isle of Man',
                        'Israel',
                        'Italy',
                        'Jamaica',
                        'Japan',
                        'Kazakhstan',
                        'Latvia',
                        'Lebanon',
                        'Macao',
                        'Macedonia',
                        'Malaysia',
                        'Mauritania',
                        'Mexico',
                        'Morocco',
                        'Netherlands',
                        'New Zealand',
                        'Nicaragua',
                        'Norway',
                        'Pakistan',
                        'Palestine',
                        'Panama',
                        'Paraguay',
                        'Peru',
                        'Philippines',
                        'Poland',
                        'Portugal',
                        'Puerto Rico',
                        'Qatar',
                        'Republic of Korea',
                        'Republic of Moldova',
                        'Romania',
                        'Russia',
                        'Saint Martin',
                        'Saudi Arabia',
                        'Senegal',
                        'Serbia',
                        'Singapore',
                        'Slovenia',
                        'South Africa',
                        'Spain',
                        'Sweden',
                        'Switzerland',
                        'Taiwan',
                        'Thailand',
                        'Trinidad and Tobago',
                        'Tunisia',
                        'Turkey',
                        'Ukraine',
                        'United Arab Emirates',
                        'United Kingdom',
                        'United States',
                        'Uruguay',
                        'Venezuela',
                        'Vietnam',
                        'Yemen'
                    ]);
            })
            .then(done)
            .catch(done);
    });
});