'use strict';

const assert = require('assert');
const API = require('./api');

describe('Game', function () {
    before(() => {
        require('../../app/index');
    });

    it('get all games', (done) => {
        API.getGames()
            .then(res => {
                assert.deepEqual(res.body, [
                    ['', 'Any game'],
                    ['1941', '1941 - Counter Attack'],
                    ['1944', '1944 - the loop master'],
                    ['19xx', '19XX - the war against destiny'],
                    ['2020bb', '2020 Super Baseball'],
                    ['3countb', '3 Count Bout'],
                    ['sonicwi2', 'Aero Fighters 2'],
                    ['sonicwi3', 'Aero Fighters 3'],
                    ['aodk', 'Aggressors of Dark Kombat'],
                    ['agallet', 'Air Gallet'],
                    ['avsp', 'Alien vs Predator'],
                    ['alpham2', 'Alpha Mission II'],
                    ['androdun', 'Andro Dunos'],
                    ['armwar', 'Armored Warriors'],
                    ['aof', 'Art of Fighting'],
                    ['aof2', 'Art of Fighting 2'],
                    ['aof3', 'Art of Fighting 3 - the path of the warrior'],
                    ['bangbead', 'Bang Bead'],
                    ['bstars2', 'Baseball Stars 2'],
                    ['batcir', 'Battle Circuit'],
                    ['flipshot', 'Battle Flip Shot'],
                    ['blazstar', 'Blazing Star'],
                    ['bjourney', 'Blue\'s Journey'],
                    ['breakers', 'Breakers'],
                    ['breakrev', 'Breakers Revenge'],
                    ['burningf', 'Burning Fight'],
                    ['dino', 'Cadillacs & Dinosaurs'],
                    ['csclub', 'Capcom Sports Club'],
                    ['captcomm', 'Captain Commando'],
                    ['cawing', 'Carrier Air Wing'],
                    ['crsword', 'Crossed Swords'],
                    ['cthd2003', 'Crouching Tiger Hidden Dragon 2003 (bootleg)'],
                    ['cyberlip', 'Cyber-Lip'],
                    ['cybots', 'Cyberbots - fullmetal madness'],
                    ['dimahoo', 'Dimahoo'],
                    ['ddonpach', 'DoDonPachi'],
                    ['donpachi', 'DonPachi'],
                    ['doubledr', 'Double Dragon'],
                    ['ddsom', 'Dungeons & Dragons - Shadow over Mystara'],
                    ['ddtod', 'Dungeons & Dragons - Tower of Doom'],
                    ['ecofghtr', 'Eco Fighters'],
                    ['eightman', 'Eight Man'],
                    ['esprade', 'ESP Ra.De.'],
                    ['fatfury1', 'Fatal Fury - king of fighters'],
                    ['fatfury2', 'Fatal Fury 2'],
                    ['fatfury3', 'Fatal Fury 3'],
                    ['fatfursp', 'Fatal Fury Special'],
                    ['feversos', 'Fever SOS'],
                    ['fightfev', 'Fight Fever'],
                    ['ffight', 'Final Fight'],
                    ['fbfrenzy', 'Football Frenzy'],
                    ['forgottn', 'Forgotten Worlds'],
                    ['gaia', 'Gaia Crusaders'],
                    ['galaxyfg', 'Galaxy Fight - universal warriors'],
                    ['ganryu', 'Ganryu'],
                    ['garou', 'Garou - Mark Of The Wolves'],
                    ['ghostlop', 'Ghostlop [Prototype]'],
                    ['ghouls', 'Ghouls\'n Ghosts'],
                    ['gigawing', 'Giga Wing'],
                    ['goalx3', 'Goal! Goal! Goal!'],
                    ['guwange', 'Guwange'],
                    ['hsf2', 'Hyper Street Fighter 2'],
                    ['jojon', 'JoJo\' Venture'],
                    ['jojoban', 'JoJo\'s Bizarre Adventure'],
                    ['kabukikl', 'Kabuki Klash - far east of eden'],
                    ['karatblz', 'Karate Blazers'],
                    ['karnovr', 'Karnov\'s Revenge'],
                    ['kodu', 'King of Dragons'],
                    ['kof94', 'King of Fighters \'94'],
                    ['kof95', 'King of Fighters \'95'],
                    ['kof96', 'King of Fighters \'96'],
                    ['kof97', 'King of Fighters \'97'],
                    ['kof98', 'King of Fighters \'98'],
                    ['kof99', 'King of Fighters \'99'],
                    ['kf2k5uni', 'King of Fighters 10th Anniversary 2005 Unique (bootleg of kof2002)'],
                    ['kof2000', 'King of Fighters 2000'],
                    ['kof2001', 'King of Fighters 2001'],
                    ['kof2002', 'King of Fighters 2002'],
                    ['kof2003', 'King of Fighters 2003'],
                    ['kof2k4se', 'King of Fighters Special Edition 2004'],
                    ['kotm', 'King of the Monsters'],
                    ['kotm2', 'King of the Monsters 2 - the next thing'],
                    ['kizuna', 'Kizuna Encounter - super tag battle'],
                    ['knights', 'Knights of the Round'],
                    ['lastblad', 'Last Blade'],
                    ['lastbld2', 'Last Blade 2'],
                    ['lresort', 'Last Resort'],
                    ['lbowling', 'League Bowling'],
                    ['msword', 'Magic Sword'],
                    ['magdrop2', 'Magical Drop II'],
                    ['magdrop3', 'Magical Drop III'],
                    ['mmatrix', 'Mars Matrix'],
                    ['msh', 'Marvel Super Heroes'],
                    ['mshvsf', 'Marvel Super Heroes vs Street Fighter'],
                    ['mvsc', 'Marvel vs Capcom'],
                    ['mmancp2u', 'Mega Man - The Power Battle'],
                    ['megaman2', 'Mega Man 2 - The Power Fighters'],
                    ['mercs', 'Mercs'],
                    ['mslug', 'Metal Slug - super vehicle-001'],
                    ['mslug2', 'Metal Slug 2 - super vehicle-001/II'],
                    ['mslug3', 'Metal Slug 3'],
                    ['mslug4', 'Metal Slug 4'],
                    ['ms5plus', 'Metal Slug 5 Plus (bootleg)'],
                    ['mslug3b6', 'Metal Slug 6 [Bootleg, bootleg of Metal Slug 3]'],
                    ['mslugx', 'Metal Slug X'],
                    ['mpang', 'Mighty! Pang'],
                    ['miexchng', 'Money Puzzle Exchanger'],
                    ['mutnat', 'Mutation Nation'],
                    ['neobombe', 'Neo Bomberman'],
                    ['turfmast', 'Neo Turf Masters'],
                    ['neocup98', 'Neo-Geo Cup \'98 - the road to the victory'],
                    ['nitd', 'Nightmare in the Dark'],
                    ['ncombat', 'Ninja Combat'],
                    ['ncommand', 'Ninja Commando'],
                    ['ninjamas', 'Ninja Masters'],
                    ['overtop', 'OverTop'],
                    ['panicbom', 'Panic Bomber'],
                    ['pgoal', 'Pleasure Goal - 5 on 5 mini soccer'],
                    ['matrim', 'Power Instinct Matrimelee'],
                    ['pspikes2', 'Power Spikes II'],
                    ['preisle2', 'Prehistoric Isle 2'],
                    ['progear', 'Progear'],
                    ['pulstar', 'Pulstar'],
                    ['pzloop2', 'Puzz Loop 2'],
                    ['pbobblen', 'Puzzle Bobble'],
                    ['pbobbl2n', 'Puzzle Bobble 2'],
                    ['uopoko', 'Puzzle Uo Poko'],
                    ['rotd', 'Rage of the Dragons'],
                    ['ragnagrd', 'Ragnagard'],
                    ['rbff1', 'Real Bout Fatal Fury'],
                    ['rbff2', 'Real Bout Fatal Fury 2'],
                    ['rbffspec', 'Real Bout Fatal Fury Special'],
                    ['redeartn', 'Red Earth'],
                    ['ringdest', 'Ring of Destruction - slammasters II'],
                    ['samsho', 'Samurai Shodown'],
                    ['samsho2', 'Samurai Shodown II'],
                    ['samsho3', 'Samurai Shodown III'],
                    ['samsho4', 'Samurai Shodown IV - Amakusa\'s revenge'],
                    ['samsho5', 'Samurai Shodown V'],
                    ['samsh5sp', 'Samurai Shodown V Special'],
                    ['slammast', 'Saturday Night Slam Masters'],
                    ['savagere', 'Savage Reign'],
                    ['sengoku', 'Sengoku'],
                    ['sengoku2', 'Sengoku 2'],
                    ['sengoku3', 'Sengoku 3'],
                    ['shocktro', 'Shock Troopers'],
                    ['shocktr2', 'Shock Troopers - 2nd squad'],
                    ['spinmast', 'Spin Master'],
                    ['sfa', 'Street Fighter Alpha'],
                    ['sfa2', 'Street Fighter Alpha 2'],
                    ['sfa3', 'Street Fighter Alpha 3'],
                    ['sf2', 'Street Fighter II'],
                    ['sf2ce', 'Street Fighter II\''],
                    ['sf2koryu', 'Street Fighter II\' - champion edition (Hack - kouryu)'],
                    ['sfiii2n', 'Street Fighter III 2nd Impact: Giant Attack'],
                    ['sfiii3n', 'Street Fighter III 3rd Strike'],
                    ['sfiii3an', 'Street Fighter III 4th Strike (Hack)'],
                    ['sfiiin', 'Street Fighter III: New Generation'],
                    ['sfz2aa', 'Street Fighter Zero 2 Alpha'],
                    ['strhoop', 'Street Hoop'],
                    ['strider', 'Strider'],
                    ['s1945p', 'Strikers 1945 plus'],
                    ['sdodgeb', 'Super Dodge Ball'],
                    ['sgemf', 'Super Gem Fighter Mini Mix'],
                    ['spf2t', 'Super Puzzle Fighter II Turbo'],
                    ['ssideki', 'Super Sidekicks'],
                    ['ssideki2', 'Super Sidekicks 2 - the world championship'],
                    ['ssideki3', 'Super Sidekicks 3 - the next glory'],
                    ['ssf2', 'Super Street Fighter II - the new challengers'],
                    ['ssf2xj', 'Super Street Fighter II X'],
                    ['svcplus', 'SvC Chaos - SNK vs Capcom Plus'],
                    ['tws96', 'Tecmo World Soccer \'96'],
                    ['punisher', 'The Punisher'],
                    ['ssideki4', 'The Ultimate 11 - SNK football championship'],
                    ['3wonders', 'Three Wonders'],
                    ['theroes', 'Thunder Heroes'],
                    ['tophuntr', 'Top Hunter - Roddy & Cathy'],
                    ['twinspri', 'Twinklestar Sprites'],
                    ['vampjr1', 'Vampire - the night warriors'],
                    ['vhuntjr2', 'Vampire Hunter - darkstalkers\' revenge'],
                    ['vhunt2', 'Vampire Hunter 2 - darkstalkers revenge'],
                    ['vsav', 'Vampire Savior'],
                    ['vsav2', 'Vampire Savior 2'],
                    ['varth', 'Varth - operation thunderstorm'],
                    ['gowcaizr', 'Voltage Fighter Gowcaizer'],
                    ['wakuwak7', 'Waku Waku 7'],
                    ['wof', 'Warriors of Fate'],
                    ['willow', 'Willow'],
                    ['wjammers', 'Windjammers'],
                    ['wh1', 'World Heroes'],
                    ['wh2', 'World Heroes 2'],
                    ['wh2j', 'World Heroes 2 Jet'],
                    ['whp', 'World Heroes Perfect'],
                    ['xmcota', 'X-Men - Children Of The Atom'],
                    ['xmvsf', 'X-Men vs Street Fighter'],
                    ['zupapa', 'Zupapa'],
                ]);
            })
            .then(done)
            .catch(done);
    });
});